### ISSUE TITLE
Readme + Contributors Guide?

### ISSUE THREAD

**Issue by kingnebby** [prbc/farese#24]
Looked at the issue for cleaning up the jpg's and wanted to do it. But not sure how you guys want others to get started?

**Comment by dbirks** [comment]
Thanks for bringing this up. Just updated the readme with 04aa2bd54e16012355d6572cef98d134943d41dd.

**Comment by kingnebby** [comment]
Awesome, I'll try to get it setup locally sometime this week and let you know how it goes. Maybe I'll leave this open until I get the code setup? Thanks.

**Comment by dbirks** [comment]
Hey cool, yeah let's leave it open. Let me know if you run into any problems.

**Comment by kingnebby** [comment]
This looks good, I might just add to the readme that the site is all static so opening index.html in the browser is as good as running the site.

**Comment by dbirks** [comment]
Ok that sounds good
