### ISSUE TITLE
Automatically build the Docker image

### ISSUE THREAD

**Issue by dbirks** [prbc/farese#26]
Currently the docker image needs to be built manually. I'm looking into Jenkins to do it automatically.

**Comment by mplorentz** [comment]
If we make the docker file `git clone` the repo when it is built, would that prevent the need for Jenkins?

**Comment by dbirks** [comment]
I don't know what would trigger the docker image to be built though. Only way I can think of is with Mr. Jen Kins.

**Comment by dbirks** [comment]
Hey, Docker Hub has github integration and can do an automated build. I've been testing it, and it usually takes about 5 minutes or less to show up on docker, which sounds good enough for me. 

Helpful links:
[Documentation on configuring an automated build](https://docs.docker.com/docker-hub/github/)

[How to make my organization membership public](https://help.github.com/articles/publicizing-or-hiding-organization-membership/)

This wonderful [comment](https://forums.docker.com/t/cant-access-new-github-organization-for-automated-builds/1080/13) to make the automated build link
