### ISSUE TITLE
Home link is broken

### ISSUE THREAD

**Issue by kingnebby** [prbc/farese#27]
In the nav bar each page is looking for `index.htm` but the file name is actually `index.html`.

Can I just rename the file? Or will docker break? I've never worked with docker and don't have it installed yet.

**Comment by dbirks** [comment]
Oh you're right. I had renamed it to html because I didn't have nginx configured correctly. I'll check that it's configured correctly in the docker image tonight.

**Comment by dbirks** [comment]
Renamed the index with 2a944f3fc8cdfada5347accba20706a2419311da, and made sure the webserver in docker will load it with #29.
