### ISSUE TITLE
TRBC appears in legacy but not in map

### ISSUE THREAD

**Issue by mplorentz** [prbc/farese#33]
From Peggy Bolles:
> Now that’s interesting….TRBC is on the Legacy page (although I find Legacy to be an odd term) but does not appear to be on the map!  At least I couldn’t find it and it’s right above Anaheim.

TRBC is Trinity Reformed Baptist Church  14407 E. Rosecrans Ave. La Mirada, CA 90638.

**Comment by dbirks** [comment]
Hmm, I'm seeing it on the map currently at least:

![screenshot from 2018-09-05 21-28-31](https://user-images.githubusercontent.com/7545665/45129618-cd9f3d80-b152-11e8-9c67-bdf7a780ef10.png)

Closing for now.
