### ISSUE TITLE
Cannot pan map on iOS

### ISSUE THREAD

**Issue by mplorentz** [prbc/farese#41]
If I open the map in Safari on my iPhone or iPad and try to pan the map does not move.

**Comment by dbirks** [comment]
Ok, it's working now in my tests. (in Safari on iPad mini with iOS 12)

Can you also check when you get a sec?

**Comment by dbirks** [comment]
I believe this is fixed.

**Comment by mplorentz** [comment]
I just tested and i can pan on my iPhone X on iOS 13.

**Comment by dbirks** [comment]
Sick :man_cartwheeling:
