### ISSUE TITLE
Add Pilgrims Reformed Baptist Church, ND

### ISSUE THREAD

**Issue by dbirks** [prbc/farese#48]
Noticed them on a google search

**Comment by hoppities** [comment]
Why not make it so that churches can claim their own profiles so that they could manage their own data?

**Comment by dbirks** [comment]
I think just because of the overhead of having to vet who gets access to edit a church, and also it would make the site more than a static site. Thank you for the idea though :+1:

**Comment by dbirks** [comment]
Closed by 2c74857
