### ISSUE TITLE
Add hamburger icon for navigation

### ISSUE THREAD

**Issue by dbirks** [prbc/farese#6]
Looking into adding a hamburger icon to float in the top left corner. 

Right now, thinking of having it display:
- Map
- Directory (like a text directory or something)
- Contact (so people can request changes to the directory)

I think these could use better names, so let me know if you can think of any.

**Comment by mplorentz** [comment]
I think a tab bar across the top would work better than a hamburger on desktop icons. That way you can see the other page titles without clicking on the hamburger. Some Wordpress themes have a feature where the tab bar across the top collapses into a vertical menu or a hamburger button on smaller screen sizes. Maybe that would be the best of both worlds?

**Comment by dbirks** [comment]
Tabs sound like a good idea. We might be able to skip the hamburger icon completely with just 3 tabs, but I'm not sure they would fit on low resolution phone screens. I'll look for responsive tabs that collapse into a hamburger icon.

**Comment by dbirks** [comment]
I really like this one: https://github.com/ChrisTheButcher/tabs-to-dropdown. There's a demo in his readme to see it in action. It doesn't have a hamburger, but instead tucks tabs into a `...` icon on the right. The demo's top bar changes height based on screen width, but I'll see if I can change it to always be thin.

**Comment by dbirks** [comment]
Ok, got it workable with 2320d9c591c7b4755f423c784541e09caf904b5f. Still need to eventually:
- change default colors
- change home symbol to name of website (maybe? Reformed Baptist Directory is kinda long. Maybe abbreviate it to RBD when on a small screen?)

**Comment by mplorentz** [comment]
That looks great!

**Comment by dbirks** [comment]
Oh good!
