### ISSUE TITLE
Add an About page

### ISSUE THREAD

**Issue by mplorentz** [prbc/farese#7]
It would be nice to have a page explaining who we are and why we are doing this. Some place to inform users that:
- We're from PRBC
- We're inspired by Johnny Farese
- This isn't an official denomination thing, because Reformed Baptists are just a bunch of independent churches
- Code is on Github

**Comment by mplorentz** [comment]
I'd be happy to write up some prose for this if you want @dbirks.

**Comment by dbirks** [comment]
That would be great. Thanks!

**Comment by dbirks** [comment]
Hey @mplorentz, I just added a contact page and removed the link to the text directory because it isn't ready yet. I'm not attached to the contact page at all, so please feel free to make changes and additions when you have a sec. I'm sure it could be written/designed better.
