### ISSUE TITLE
Add text directory

### ISSUE THREAD

**Issue by dbirks** [prbc/farese#8]
I'm thinking of adding a text directory that would have basically all the info that Farese.com has, ordered by state or country, all on one page. To quickly jump to a certain section, I was thinking of making a list of links at the top that would jump to the correct div tag for that country.

To make the page with jQuery, I was thinking of grabbing the name, address, and website from data.json, and make an additional .json file to hold the rest of the info like the pastor's name and phone number in a text block for each church. To identify each church in each file, I would make a 2 or 3 character church ID so I could look each one up by that.

If there's a better, or at least, alternative way to do this, I'm all :ear::ear::ear:. :smile:

**Comment by mplorentz** [comment]
For this small of a data set, you could just keep all the data in data.json and just ignore the information you don't want to display on the map. That would keep things simple for now. Thoughts?

**Comment by dbirks** [comment]
Sounds good. That'll be a lot simpler. I was worried about the size of data.json, but it looks like it is currently only 144 KB, and surely adding the rest of the data wouldn't even double it, so yeah, I think we're good.

**Comment by dbirks** [comment]
Got some simple cards up with 401d2bfc63fad4474c222603815e8f9dc5ea51f0. First off, is there a better way to display the churches rather than cards?

Also, I was thinking of adding a navigation bar on the left side (like the one on [this page](http://bootcards.org/site/docs.html)) that would update as you scroll through the document by looking at div id tags. That would be fine for the desktop, but I'm trying to figure out how to display navigation on phone screens without using a hamburger menu. Maybe just display buttons that expose a small nested list of countries and states at the top of the page on mobile? I found an example of some buttons [here](https://developer.github.com/v3/) on the right side of the page. I think we would only need six buttons for the continents. I can't think of any other way to do it. Any ideas @mplorentz?

**Comment by dbirks** [comment]
Just thinking out loud, maybe it would be acceptable for the side navigation to disappear if we included a search button. I could try to get it to search by location using the Mapbox geocoder, and then list the churches that are closest to those coordinates. 

We can talk about it later.

**Comment by dbirks** [comment]
Been thinking about this some more. Maybe we should leave the side navigation off for now, and just focus on getting a text directory up that can be linked to from the map. (Getting it so that there's a "show more" link on each church on the map that will jump to the church listing on the text directory.)

Also, I think the cards might not be the best idea for the desktop view. Maybe something more like a normal table view, with columns for church name, street address, city, state/province, nation. I think we can change css style based on screen width with that `@media` magic, and display the table as cards on small screens.

**Comment by dbirks** [comment]
Ok, we decided to keep the current site the way it is for the text directory. We just need to update the current site with the new data (see #17).

Since we currently have a text directory though, I'm closing this.
