### ISSUE TITLE
Change header bar colors

### ISSUE THREAD

**Issue by dbirks** [prbc/farese#9]
Opening a separate issue so I can close #6 for a sense of accomplishment. :P 

I personally think a light theme would look good. I'm thinking maybe a white bar with green or blue accents would be good, but might be too basic looking. I'll post ideas as I think of them.

**Comment by dbirks** [comment]
Here's just some ideas. I'll hopefully put some more up in a bit.

<img width="337" alt="2" src="https://cloud.githubusercontent.com/assets/7545665/12868940/231da5ee-cce0-11e5-84f8-4655066f6e42.png">
<img width="337" alt="3" src="https://cloud.githubusercontent.com/assets/7545665/12868942/231e3e6e-cce0-11e5-9e53-beeb858c2ea9.png">
<img width="337" alt="4" src="https://cloud.githubusercontent.com/assets/7545665/12868941/231dc290-cce0-11e5-963e-932dc7b137f9.png">
<img width="338" alt="5" src="https://cloud.githubusercontent.com/assets/7545665/12868938/231c78a4-cce0-11e5-8b19-52d76913165b.png">

**Comment by dbirks** [comment]
In e65dfa4b0178252eb2209dd0b32d0419e228fc64, decided to go with blueberry colors, and switched the home button to have the darker color. Also replaced the home symbol with the site name, and switched to [Pacifico](https://www.google.com/fonts/specimen/Pacifico) for the title font. 

<img width="338" alt="6" src="https://cloud.githubusercontent.com/assets/7545665/12904645/d0ba8568-ce9e-11e5-9a58-03a265c2ccaf.png">

I am _very_ open to ideas about a different color palette and font choices. Just wanted to get something up. Leaving open for possible discussion.

**Comment by mplorentz** [comment]
is broke https://forums.developer.apple.com/thread/9819
